### ISSUE TITLE
考虑做一下获取ptt的方法么

### ISSUE THREAD

**Issue by kagg886** [ChinaYuanGe/ArcaeaScoreReader#1]
萌新不会(((

**Comment by ChinaYuanGe** [comment]
> 萌新不会(((

可以是可以，就是需要找新的偏移才能读，如果初级指针不是在同一片区域内就麻烦一点。

**Comment by kagg886** [comment]
这样啊，我不太会找(
我刚刚拿gg修改器搜了一下ptt的浮点数，浮点hex，硬是没搜出来(
主要是，如果能获取到内存中的ptt数据，我应该就可以反推r10了(
https://github.com/kagg886/ArcaeaB30Fucker
